(function () {
  // Function to sanitize cookie values (remove tabs, newlines, etc.)
  function sanitizeValue(value) {
      return value.replace(/[\t\n\r]/g, '');
  }

  // Extract cookies from document.cookie
  let cookies;
  try {
      cookies = document.cookie.split(';').map(cookie => {
          const trimmed = cookie.trim();
          if (!trimmed) return null;
          const [name, ...valueParts] = trimmed.split('=');
          const value = valueParts.join('='); // Handle values containing '='
          return { name: sanitizeValue(name), value: sanitizeValue(value) };
      }).filter(cookie => cookie && cookie.name && cookie.value); // Filter out invalid cookies
  } catch (e) {
      console.error('Error accessing cookies:', e);
      return ['# Error: Unable to access cookies. Ensure this script is run in a browser console.'];
  }

  // Get domain and protocol
  const domain = window.location.hostname;
  const isSecureProtocol = window.location.protocol === 'https:';

  // Initialize Netscape cookie file format
  const netscapeCookies = [
      '# Netscape HTTP Cookie File',
      '# This is a generated file! Do not edit.',
      '# Generated by JavaScript console script',
      '# Note: This script only captures non-HttpOnly cookies for the current domain.',
      '# For complete cookies, use a browser extension like "Export Cookies".',
      ''
  ];

  // Process each cookie
  cookies.forEach(cookie => {
      const line = [
          domain,                         // Domain (e.g., www.youtube.com)
          'TRUE',                         // Flag: TRUE for all subdomains
          '/',                            // Path: Default to root
          isSecureProtocol ? 'TRUE' : 'FALSE', // Secure: TRUE if HTTPS, else FALSE
          '0',                            // Expiration: 0 for session cookies
          cookie.name,                    // Cookie name
          cookie.value                    // Cookie value
      ].map(field => field.toString()).join('\t'); // Ensure tab-separated
      netscapeCookies.push(line);
  });

  // Output to console
  const output = netscapeCookies.join('\n');
  console.log(output);

  // Optional: Create a downloadable file
  try {
      const blob = new Blob([output], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'cookies.txt';
      a.click();
      URL.revokeObjectURL(url);
      console.log('Cookies file downloaded as cookies.txt');
  } catch (e) {
      console.warn('Could not trigger download:', e);
      console.log('Please copy the console output and save it as cookies.txt');
  }

  return output;
})();