FROM --platform=linux/amd64 docker.io/library/debian:bookworm-slim 

COPY files/sources.list /sources.list
RUN cat /sources.list > /etc/apt/sources.list 
RUN rm /etc/apt/sources.list.d/* && rm /sources.list

RUN apt update && apt upgrade -y \
    && apt --fix-broken install \
    && apt install \
    gstreamer1.0-libav gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    libx265-199 x264 libx264-164 pulseaudio libpulse0 pulseaudio-utils dbus bluez bluetooth \
    ffmpeg libdav1d6 libavcodec-extra libmpeg2-4 libtheora0 libxvidcore4 \
    alsa-oss alsa-utils ca-certificates vlc -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

ARG GROUP_ID=9814
ARG USER_ID=9814
ARG USRNME=mgibson

RUN groupadd --system -g $GROUP_ID $USRNME
RUN useradd --system --create-home -u $USER_ID -g $GROUP_ID $USRNME
RUN usermod -aG audio,video,bluetooth $USRNME

COPY files/daemon.conf /etc/pulse/daemon.conf
COPY files/pulse-client.conf /etc/pulse/client.conf

RUN mkdir -p /run/user/${USER_ID}/ && chown -R ${USER_ID}:${USER_ID} /run/user/${USER_ID}/ && chmod 700 /run/user/${USER_ID}

#RUN echo "default-server = unix:/run/user/$USER_ID/pulse/native" >> /etc/pulse/client.conf

USER $USRNME
RUN echo $(pulseaudio -k ) && echo $(pulseaudio --start | true)

