FROM --platform=linux/amd64 docker.io/library/debian:latest 

COPY files/sources.list /sources.list
RUN cat /sources.list > /etc/apt/sources.list 
RUN rm /etc/apt/sources.list.d/* && rm /sources.list

RUN apt update && apt upgrade -y \
    && apt install apt-transport-https \
    gstreamer1.0-libav gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    libx265-199 x264 libx264-164 dbus \
    ffmpeg libdav1d6 libavcodec-extra libmpeg2-4 libtheora0 libxvidcore4 \
    bluetooth bluez alsa-oss alsa-utils pulseaudio ca-certificates vlc parole -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

ARG GROUP_ID=1000
ARG USER_ID=1000
ARG USRNME=mgibson

RUN groupadd --system -g $GROUP_ID $USRNME
RUN useradd --system --create-home -u $USER_ID -g $GROUP_ID -G audio,video,bluetooth $USRNME
RUN mkdir -p /home/$USRNME/.config \
    && mkdir -p /home/$USRNME/.cache \
    && mkdir -p /home/$USRNME/.local/share \
    && chown --recursive $USRNME:$USRNME /home/$USRNME

COPY files/daemon.conf /etc/pulse/daemon.conf
COPY files/pulse-client.conf /etc/pulse/client.conf

RUN echo "default-server = unix:/run/user/$USER_ID/pulse/native" >> /etc/pulse/client.conf

USER $USRNME
RUN mkdir -p /tmp/xdg

CMD "vlc"
