FROM docker.io/library/debian:latest

COPY sources.list /sources.list
RUN cat /sources.list > /etc/apt/sources.list 
RUN rm /etc/apt/sources.list.d/* && rm /sources.list

RUN apt update && apt upgrade -y && apt --fix-broken install \
    apt install -y kde-plasma-desktop

RUN apt update && apt upgrade -y && \
    apt install -y okular && \
    rm -rf /var/lib/apt/lists/*

ARG GROUP_ID=9898
ARG USER_ID=9898
ARG USRNME

RUN groupadd -g $GROUP_ID --system $USRNME && \
    useradd -m --gid $GROUP_ID --system -u $USER_ID $USRNME \
    && mkdir -p /home/$USRNME/.config \
    && mkdir -p /home/$USRNME/.cache \
    && chown --recursive $USER_ID:$GROUP_ID /home/$USRNME

USER $USRNME

CMD ["okular"]
