FROM docker.io/library/debian:latest

RUN apt update && apt upgrade -y && apt --fix-broken install -y && \
    apt install -y git neovim curl wget dbus \
    python3 python3-dev python3-venv mc python3-pip pylint pipx python3-virtualenv \
    build-essential libssl-dev libffi-dev libpq-dev xfce4 libnss3-dev libdbus-1-3 \
    && apt clean && rm -rf /var/lib/apt/lists/*

ARG GROUP_ID=9898
ARG USER_ID=9898
ARG USRNME=vscoder
ARG GIT_EMAIL=mikhailowvw@gmail.com
ARG GIT_NAME='"Viacheslav Mikhailov"'

RUN groupadd --gid $GROUP_ID --system $USRNME && \
    useradd --create-home --gid $GROUP_ID --system --uid $USER_ID $USRNME \
    && mkdir --parents /home/$USRNME/.config \
    && mkdir --parents /home/$USRNME/.cache \
    && mkdir --parents /home/$USRNME/.local/share \
    && chown --recursive $USRNME:$USRNME /home/$USRNME

WORKDIR /home/$USRNME
RUN JDK24_SHA256SUM=$(curl https://download.java.net/java/GA/jdk24.0.1/24a58e0e276943138bf3e963e6291ac2/9/GPL/openjdk-24.0.1_linux-x64_bin.tar.gz.sha256) \
    && curl -o jdk24.tar.gz  https://download.java.net/java/GA/jdk24.0.1/24a58e0e276943138bf3e963e6291ac2/9/GPL/openjdk-24.0.1_linux-x64_bin.tar.gz \
    && JDK24_ACTUAL_SHA256SUM=$(sha256sum jdk24.tar.gz) \
    && if [ $JDK24_ACTUAL_SHA256SUM != $JDK24_SHA256SUM ]; then \
            echo "Error: The sha256sum of the file does not match the expected value."; \
            echo "Expected: $JDK24_SHA256SUM"; \
            echo "Actual:   $JDK23_ACTUAL_SHA256SUM"; \
            exit 1; \
        fi

COPY entrypoint_wlnd.sh /entrypoint.sh
RUN chmod ugo+x /entrypoint.sh

RUN tar -xzvf jdk24.tar.gz -C .
COPY code-stable-x64-*.tar.gz /home/$USRNME/vscode.tar.gz
RUN tar xf vscode.tar.gz -C .
RUN chown -R 9898:9898 .
USER $USRNME
RUN git config --global user.email $GIT_EMAIL
RUN git config --global user.name $GIT_NAME
ENV usrnme=${USRNME}
ENTRYPOINT /entrypoint.sh $usrnme
