#Благодаря: https://www.opennet.ru/tips/info/3141.shtml
#Не забудьте выяснить поддерживаемые форматы вашим железом командой aplay --device hw /dev/urandom --dump-hw-params
default-sample-format = s32le # Варианты s16le, s32le, float32le
default-sample-rate = 192000 # как вариант 48000, 96000, 192000, 320000 
alternate-sample-rate = 44100 # как вариант 44100, 88200
default-sample-channels = 2
default-channel-map = front-left,front-right
#Уменьшение числа и увеличение размера буферов воспроизведения
default-fragments = 2 # по умолчанию 4
default-fragment-size-msec = 125 # по умолчанию 25
resample-method = soxr-vhq # Варианты src-sinc-best-quality, soxr-vhq, copy, speex-float-1
#enable-lfe-remixing = no #yes для 2+1, 5+1 и т.д.
remixing-produce-lfe=no #yes для 2+1, 5+1 и т.д.
remixing-consume-lfe=no #yes для 2+1, 5+1 и т.д. 
#lfe-crossover-freq = 250 # включить для 2+1, 5+1 и т.д.
high-priority = yes
#Есть возможность пускать звук от железа на ALSA hw, то есть, мимо звукосервера. Для этого, Ваша звуковуха 
#должна поддерживать hardware mixing. Список подходящих устройств: https://www.alsa-project.org/wiki/Matrix:Tag-HWMIX
#avoid-resampling = false
nice-level = -11
realtime-scheduling = yes
realtime-priority = 9 # по умолчанию 5
rlimit-rtprio = 9
daemonize = no
